["setup.cfg".mypy]
check_untyped_defs = true

disallow_subclassing_any = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

follow_imports_for_stubs = true

ignore_missing_imports = false

no_implicit_optional = true

namespace_packages = true

pretty = false

show_error_codes = true
show_error_context = true
show_absolute_path = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
